version: '2'
services:
    perioline-app:
        image: perioline
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://perioline-postgresql:5432/perioline
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    perioline-postgresql:
        extends:
            file: postgresql.yml
            service: perioline-postgresql
